env:
  RCLONECONFIG_DRIVE: "ENCRYPTED[a38685093e5400dc45eb2bc4938f0971fbcc68a2a3037637e5d77459c6151cd27c30c0088aea52acba3638112b1ae0fa]"
  TG_TOKEN: "ENCRYPTED[39c04535f557964a338810c9cfd1746454332979cd2fc6469dbd81e5a1b88b1de280bc0fd5942e2bcb9df9dd08a58eb4]"
  TG_CHAT_ID: "ENCRYPTED[6f7d5ab23e226c3df9667dacfb61b1eb735325dff6be950c57904aba2b8826569cef8cda434548416717f19ca2cbf6b8]"
  WORKDIR: "/tmp"
  EMAIL: "ENCRYPTED[ceac5be305cbb6b620c440d1f7d568f3307fa3dec18dc8197b78381b56f623402cd3ec4589c91582dd78f4a9447b3c17]"
  CIRRUS_CLONE_DEPTH: "1"
  credentials: "ENCRYPTED[bc816deecd38644b713913a00dff42f0943d8218db9aa9a0aa07b14150a7cabd681beee38b49cdf68958fa9fb0cae187]"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'ryanzsz'
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Load-Ccache_background_script:
     - ./script/load_ccache.sh

  Sync-rom_script:
     - git config --global user.name "ryanzsz"
     - git config --global user.email "iyanz46@gmail.com"
     - echo "$credentials" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials
     - ./script/sync.sh
     
  Build-rom_script:
     - ./script/building.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/ziping.sh
